INFO:root:Running Attack of the tails with args: Namespace(adv_lr=0.02, adversarial_local_training_period=2, attack_case='edge-case', attack_method='blackbox', attacker_pool_size=100, batch_size=32, dataset='cifar10', defense_method='no-defense', device='cuda:1', epochs=14, eps=2.0, fl_mode='fixed-freq', fl_round=500, fraction=0.1, gamma=0.998, local_train_period=2, log_interval=100, lr=0.02, model='vgg16', model_replacement=False, no_cuda=False, norm_bound=2.0, num_nets=200, part_nets_per_round=10, poison_type='southwest', project_frequency=10, prox_attack=False, rand_seed=7, seed=1, stddev=0.025, test_batch_size=1000)
INFO:root:cpu
INFO:root:==> Building model..
INFO:root:Seeded everything
INFO:root:OOD (Southwest Airline) train-data shape we collected: (784, 32, 32, 3)
INFO:root:OOD (Southwest Airline) test-data shape we collected: (196, 32, 32, 3)
INFO:root:!!!!!!!!!!!Num poisoned data points in the mixed dataset: 100
INFO:root:!!!!!!!!!!!Num clean data points in the mixed dataset: 400
INFO:root:(500, 32, 32, 3)
INFO:root:(500,)
INFO:root:2795
INFO:root:GET_VGG_MODEL: Fetch vgg16
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
Traceback (most recent call last):
  File "simulated_averaging.py", line 148, in <module>
    with open("./checkpoint/Cifar10_{}_10epoch.pt".format(args.model.upper()), "rb") as ckpt_file:
FileNotFoundError: [Errno 2] No such file or directory: './checkpoint/Cifar10_VGG16_10epoch.pt'
